repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-yaml
      - id: check-toml
      - id: check-case-conflict
      - id: check-added-large-files
      - id: debug-statements
      - id: requirements-txt-fixer
      - id: mixed-line-ending
        args: ["--fix=no"]
      - id: trailing-whitespace
        args: ["--markdown-linebreak-ext=md"]
      - id: end-of-file-fixer
  - repo: https://github.com/asottile/pyupgrade
    rev: 'v2.31.1'
    hooks:
      - id: pyupgrade
        args: ["--py36-plus"]
  - repo: https://github.com/psf/black
    rev: '22.3.0'
    hooks:
      - id: black
        language_version: python3 # Should be a command that runs python3.6+
  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
        language_version: python3
  - repo: https://gitlab.com/pycqa/flake8
    rev: '4.0.1'
    hooks:
      - id: flake8
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.942'
    hooks:
      - id: mypy
        args: ["--install-types", "--non-interactive"]
        additional_dependencies:
          - bencode.py==4.0.0
          - genutility==0.0.75
          - metrohash-python==1.1.3.2
          - mutagen==1.45.1
          - Pillow>=8.1.1
          - pymongo==3.12.0
          - requests==2.26.0
          - tqdm==4.62.1
