repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  - id: check-added-large-files
  - id: check-case-conflict
  - id: check-json
  - id: check-merge-conflict
  - id: check-symlinks
  - id: check-toml
  - id: check-yaml
  - id: debug-statements
  - id: detect-private-key
  - id: end-of-file-fixer
  - id: mixed-line-ending
  - id: pretty-format-json
    args: [--autofix, --no-ensure-ascii]
  - id: requirements-txt-fixer
  - id: trailing-whitespace
    args: [--markdown-linebreak-ext=md]
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.14.0
  hooks:
  - id: pretty-format-yaml
    args: [--autofix]
- repo: https://github.com/tox-dev/pyproject-fmt
  rev: 2.2.1
  hooks:
  - id: pyproject-fmt
- repo: https://github.com/asottile/pyupgrade
  rev: v3.16.0
  hooks:
  - id: pyupgrade
    args: [--py38-plus]
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.11.10
  hooks:
  - id: ruff-check
    args: [--fix]
  - id: ruff-format
- repo: https://github.com/PyCQA/bandit
  rev: 1.7.10
  hooks:
  - id: bandit
    args: [-c, pyproject.toml]
    additional_dependencies: ['.[toml]']
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.14.1
  hooks:
  - id: mypy
    args: [--install-types, --non-interactive, --show-error-codes]
    additional_dependencies:
    - bencode.py==4.0.0
    - ctypes-windows-sdk==0.0.15
    - genutility[fileformats,filesystem,fingerprinting,hash,image,metrics,pillow,rich,torrent,tqdm,videofile]==0.0.114
    - libtorrent==2.0.9  # last version available on 3.7
    - metrictrees==0.0.1
    - metrohash-python==1.1.3.3
    - more-itertools==9.1.0  # last version available on 3.7
    - mutagen==1.47.0
    - Pillow==9.5.0  # last version available on 3.7
    - pyexiv2==2.15.3
    - pymongo==4.7.3  # last version available on 3.7
    - pypyodbc==1.3.6
    - requests==2.31.0  # last version available on 3.7
    - rich==13.8.1  # last version available on 3.7
    - scikit-image==0.19.3  # last version available on 3.7
    - typing-extensions==4.7.1  # last version available on 3.7
- repo: https://github.com/Yelp/detect-secrets
  rev: v1.5.0
  hooks:
  - id: detect-secrets
