repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: check-json
  - id: check-yaml
  - id: check-toml
  - id: check-case-conflict
  - id: check-added-large-files
  - id: debug-statements
  - id: end-of-file-fixer
  - id: mixed-line-ending
    args: [--fix=no]
  - id: requirements-txt-fixer
  - id: trailing-whitespace
    args: [--markdown-linebreak-ext=md]
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.14.0
  hooks:
  - id: pretty-format-yaml
    args: [--autofix]
- repo: https://github.com/tox-dev/pyproject-fmt
  rev: 2.2.1
  hooks:
  - id: pyproject-fmt
- repo: https://github.com/asottile/pyupgrade
  rev: v3.16.0
  hooks:
  - id: pyupgrade
    args: [--py38-plus]
- repo: https://github.com/psf/black-pre-commit-mirror
  rev: 24.4.2
  hooks:
  - id: black
- repo: https://github.com/PyCQA/isort
  rev: 5.13.2
  hooks:
  - id: isort
- repo: https://github.com/pycqa/flake8
  rev: 7.1.0
  hooks:
  - id: flake8
    additional_dependencies:
    - flake8-annotations
    - flake8-bugbear
    - flake8-eradicate
    - flake8-mutable
    - flake8-simplify
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.11.1
  hooks:
  - id: mypy
    args: [--install-types, --non-interactive, --show-error-codes]
    additional_dependencies:
    - bencode.py==4.0.0
    - ctypes-windows-sdk==0.0.15
    - genutility[image,pillow,videofile,rich,torrent]==0.0.107
    - libtorrent==2.0.9
    - metrictrees==0.0.1
    - metrohash-python==1.1.3.3
    - more-itertools==9.1.0  # last version available on 3.7
    - mutagen==1.47.0
    - Pillow==9.5.0
    - pyexiv2==2.12.0
    - pymongo==4.7.3
    - pypyodbc==1.3.6
    - requests==2.31.0
    - rich==13.7.1
    - scikit-image==0.19.3  # last version available on 3.7
    - typing-extensions==4.7.1  # last version available on 3.7
- repo: https://github.com/Yelp/detect-secrets
  rev: v1.5.0
  hooks:
  - id: detect-secrets
